replicaCount: 1

image:
  repository: haghdk/md5generator
  tag: latest
  pullPolicy: IfNotPresent
  build:
    enabled: true
    dockerfile: Dockerfile
    contextPath: ./nuxt-app

serviceAccount:
  create: true
  name: ""

autoscaling:
  enable: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: md5generator.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
